name: "Lint Packages"

on: 
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  lint:
    runs-on: 'macos-latest'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: 'Lint Packages'
        shell: bash
        run: npm run lint